<tr>
    <td>{Date}</td>
    <td>{Description}</td>
    <td>{Price}</td>
    <td>{LIkes}</td>
    <td>{Dislikes}</td>
    <td>{Views}</td>
    <td>{Shares}</td>
    <td>{Comments}</td>
    <td>{Name}</td>
    <td>{Status}</td>
</tr>
