<tr>
    <td>{Name}</td>
    <td>{SurName}</td>
    <td>{MiddleName}</td>
    <td>{Department}</td>
    <td>{Job}</td>
    <td>{Phone}</td>
    <td>{Email}</td>
    <td>{DateBirth}</td>
</tr>
