<tr>
    <td>{SurName}</td>
    <td>{MiddleName}</td>
    <td>{Email}</td>
    <td>{Phone}</td>
    <td>{DateBirth}</td>
    <td>{Address}</td>
    <td>{FamilyStatus}</td>
    <td>{Education}</td>
    <td>{Job}</td>
    <td>{Department}</td>
    <td>{Salary}</td>
</tr>
